"use client";

import { ShieldCheckIcon, ShieldOffIcon } from "lucide-react";
import { useTranslations } from "next-intl";
import { useActionState, useState, useTransition } from "react";

import { ActionMessage } from "@/components/forms/action-message";
import { SubmitButton } from "@/components/forms/submit-button";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  confirmTotpEnrollment,
  disableTotp,
  type EnrollmentState,
  startTotpEnrollment,
} from "@/server/actions/mfa";
import { idle } from "@/server/actions/admin/_shared-client";

export function TotpSetup({ enrolled, isAdmin }: { enrolled: boolean; isAdmin: boolean }) {
  const t = useTranslations("security");
  const [enrollment, setEnrollment] = useState<EnrollmentState | null>(null);
  const [pending, startTransition] = useTransition();
  const [confirmState, confirmAction] = useActionState(
    confirmTotpEnrollment,
    idle as EnrollmentState,
  );
  const [disableState, disableAction] = useActionState(disableTotp, idle);
  const active = enrolled || confirmState.status === "success";

  if (active && disableState.status !== "success") {
    return (
      <div className="flex flex-col gap-4">
        <p className="flex items-center gap-2 text-sm font-medium text-primary">
          <ShieldCheckIcon className="size-5" aria-hidden />
          {t("status.on")}
        </p>
        {isAdmin ? (
          <p className="text-sm text-muted-foreground">{t("adminCannotDisable")}</p>
        ) : (
          <form action={disableAction} className="flex flex-col gap-3">
            <p className="text-sm text-muted-foreground">{t("disableHint")}</p>
            <div className="flex flex-col gap-2">
              <Label htmlFor="disable-code">{t("code")}</Label>
              <Input
                id="disable-code"
                name="code"
                inputMode="numeric"
                autoComplete="one-time-code"
                pattern="[0-9 ]{6,7}"
                required
                className="min-h-11 w-40 tracking-widest"
              />
            </div>
            <ActionMessage status={disableState.status} message={disableState.message} />
            <SubmitButton variant="outline" className="min-h-11 sm:self-start">
              <ShieldOffIcon aria-hidden />
              {t("disable")}
            </SubmitButton>
          </form>
        )}
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <p className="text-sm text-muted-foreground">{t("status.off")}</p>
      {!enrollment?.qrCode ? (
        <Button
          type="button"
          className="min-h-11 sm:self-start"
          disabled={pending}
          onClick={() => startTransition(async () => setEnrollment(await startTotpEnrollment()))}
        >
          <ShieldCheckIcon aria-hidden />
          {t("start")}
        </Button>
      ) : (
        <form action={confirmAction} className="flex flex-col gap-4">
          <input type="hidden" name="factorId" value={enrollment.factorId} />
          <p className="text-sm">{t("scanHint")}</p>
          {/* eslint-disable-next-line @next/next/no-img-element -- data URL generated by Supabase */}
          <img
            src={enrollment.qrCode}
            alt={t("qrAlt")}
            width={200}
            height={200}
            className="rounded-xl border bg-white p-2"
          />
          <p className="text-xs text-muted-foreground">
            {t("secret")} : <code className="font-mono break-all">{enrollment.secret}</code>
          </p>
          <div className="flex flex-col gap-2">
            <Label htmlFor="code">{t("code")}</Label>
            <Input
              id="code"
              name="code"
              inputMode="numeric"
              autoComplete="one-time-code"
              pattern="[0-9 ]{6,7}"
              required
              className="min-h-11 w-40 tracking-widest"
            />
          </div>
          <ActionMessage status={confirmState.status} message={confirmState.message} />
          <SubmitButton className="min-h-11 sm:self-start">{t("confirm")}</SubmitButton>
        </form>
      )}
      {enrollment?.status === "error" && (
        <ActionMessage status="error" message={enrollment.message} />
      )}
    </div>
  );
}
